name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.0]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
    
    - name: Install git
      run: |
        sudo apt-get update && sudo apt-get install -y git
        
    - name: Publish to git
      uses: seanmiddleditch/gha-publish-to-git@v2
      with:
        branch: build
        source_folder: ./dist
        github_token: ${{ secrets.GITHUB_TOKEN }}
